POST http://localhost:4004/catalog/createRecord
Content-Type: application/json;odata.metadata=minimal

{
   "createData" : "{\"poNumber\":\"PO10\",\"itemNumber\":\"34\",\"orderNumber\":\"ORD02\",\"price\":\"112.00\",\"quantity\":\"7\",\"deliveryDate\":\"2022-11-23\",\"deviationType\":\"type1\",\"emailId\":\"sahil.kharbanda@accenture.com\",\"initialMailDate\":\"\",\"reminderDate1\":\"\",\"reminderDate2\":\"\",\"reminderDate3\":\"\",\"poUpdateFlag\":\"0\"}"
}

### Send Reminders

POST http://localhost:4004/catalog/batchReminders
Content-Type: application/json;odata.metadata=minimal

### Create operation

POST http://localhost:4004/catalog/Records
Content-Type: application/json;odata.metadata=minimal

{"poNumber":"PO10", "itemNumber": "35", "orderNumber": "ORD02", "price": "112.00", "quantity": "7", "deliveryDate": "2022-11-28", "deviationType": "type1", "emailId": "sahil.kharbanda@accenture.com" ,"initialMailDate": null,"reminderDate1": null, "reminderDate2": null, "reminderDate3": null, "poUpdateFlag": "0"}